### ISSUE TITLE
Doesn't show an error for permissions

### ISSUE THREAD

**Issue by superm1** [intel/dptfxtract#1]
I was just testing this tool on XPS 9365 and noticed that if you launch the tool as a regular user (not root), it returns a "0" return code and doesn't show an error.

I know in your README you say to run as root, but you may consider in a future version showing an error message in this scenario.

**Comment by spandruvada** [comment]
On Mon, 2017-11-20 at 15:31 +0000, Mario Limonciello wrote:
> I was just testing this tool on XPS 9365 and noticed that if you
> launch the tool as a regular user (not root), it returns a "0" return
> code and doesn't show an error.
> I know in your README you say to run as root, but you may consider in
> a future version showing an error message in this scenario.
Good point. I will add this.

Thanks,
Srinivas

**Comment by superm1** [comment]
Based on commit log it looks like this can be closed from v1.1 (haven't yet confirmed).
