### ISSUE TITLE
Lenovo 7th gen i5-7300U: No valid tables found

### ISSUE THREAD

**Issue by Maryse47** [intel/dptfxtract#10]
Hello, I have 7th gen i5-7300U processor on Lenovo Notebook and this tool refuses to work:

```
sudo dptfxtract
DPTF Tables Extraction Utility 
Copyright (c) 2000 - 2019 Intel Corporation


No valid tables found 
```

Linux kernel: 5.3.7
dptfxtract: 1.4.2
Latest OEM Bios

**Comment by spandruvada** [comment]
These are not mandatory tables, so some systems may not have any.

**Comment by Maryse47** [comment]
@spandruvada is thermald useless for my system then?

**Comment by spandruvada** [comment]
On Fri, 2019-10-18 at 08:11 -0700, Maryse47 wrote:
> @spandruvada is thermald useless for my system then?
No. There are other tables which thermald can use. Also thermald
generates its own if nothing found.
