### ISSUE TITLE
No valid tables found

### ISSUE THREAD

**Issue by danie-dejager** [intel/dptfxtract#15]
Hi,

I have a PC Specialist PC, Optimus Series with a gen 10 Intel® Core™ i7 Six Core Processor 10750H CPU. When I run the latest version as root, the output is that no valid tables are found.

![image](https://user-images.githubusercontent.com/13314239/118136247-3232f000-b404-11eb-9c7b-2f00c6ba616e.png)

**Comment by spandruvada** [comment]
Hi,

It is possible not to have support.
Any thermald version 2.0 + doesn't need this tool anymore.

Thanks.

**Comment by waltercool** [comment]
May someone add this information into README.txt? Would be helpful.

**Comment by spandruvada** [comment]
Updated README as suggested.
