### ISSUE TITLE
Consider placing conf file in /etc/thermald instead

### ISSUE THREAD

**Issue by superm1** [intel/dptfxtract#2]
Since the directory `/var/run/thermald` is ephemeral, this tool would need to be run on every boot.

Would you consider to instead by default install to `/etc/thermald`?  Or offer a configuration option of where to place files?  This should let the application only need to be run once per machine.

**Comment by spandruvada** [comment]
On Mon, 2017-11-20 at 15:39 +0000, Mario Limonciello wrote:
> Since the directory /var/run/thermald is ephemeral, this tool would
> need to be run on every boot.
> Would you consider to instead by default install to /etc/thermald? Or
> offer a configuration option of where to place files? This should let
> the application only need to be run once per machine.
I will let this configurable from command line in the next revision.

Thanks,
Srinivas

**Comment by superm1** [comment]
Based on commit log it looks like this can be closed from v1.1 (haven't yet confirmed).
