### ISSUE TITLE
Can't run as non-root user

### ISSUE THREAD

**Issue by anthonywong** [intel/dptfxtract#4]
Since `dptfxtract` is binary only I want to run it as a non-root user, like this:

1. As root, use `acpidump` and `acpixtract` to retrieve ACPI tables
2. As a non-root user, use `dptfxtract` to generate thermald config file.
3. As root, copy thermald config file over to `/etc/thermald`

However, dptfxtract is required to be run as root even when I run `dptfxtract *.dat -o $OUTPUT`.

**Comment by Vaesper** [comment]
The readme explicitly states this usecase but the binary does not allow it.

**Comment by thinrope** [comment]
@spandruvada Can you at least comment why you decided to close this issue?

This utility, supplied as a binary blob, should not require root privileges from the start. It doesn't even print help or version info without root!
```bash
$ dptfxtract -h
You must be root to run this tool!
```

**Comment by spandruvada** [comment]
Anything done in this utility now done in open source in thermald (even with more features). So try without running this utility.
