### ISSUE TITLE
Generated configuration appears non-functional on XPS 9370

### ISSUE THREAD

**Issue by benzea** [intel/dptfxtract#6]
Hi,

I updated thermald to 1.8 in Fedora and also packaged and installed dptfxtract v1.3. However, I am not seeing any difference on the machine, i.e. the overall performance characteristics do not seem to change between setting thermald to disabled/performance/energy conserver.

I tested this with stress-ng (matrixprod) and an ffmpeg h264 encode run. What I am seeing is that there is an initial spike in CPU temperature and the performance is then throttled down so that the CPU consistently stays below 75°C.

Now, this may also be an issue with thermald not being able to function appropriately. I am attaching the "debug" level log and the generated configuration.

[thermald.log](https://github.com/intel/dptfxtract/files/3198163/thermald.log)

[thermal-conf.xml.auto.txt](https://github.com/intel/dptfxtract/files/3198168/thermal-conf.xml.auto.txt)

While running, I started a CPU intensive task shortly before `May 20 09:40:55 localhost.localdomain kernel`, which is when I got MCE critical errors:

```
May 20 09:40:55 localhost.localdomain kernel: mce: CPU4: Core temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU6: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU7: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU0: Core temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU2: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU3: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU0: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU4: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU5: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU1: Package temperature above threshold, cpu clock throttled (total events = 1)
May 20 09:40:55 localhost.localdomain kernel: mce: CPU4: Core temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU7: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU6: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU2: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU1: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU5: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU0: Core temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU3: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU0: Package temperature/speed normal
May 20 09:40:55 localhost.localdomain kernel: mce: CPU4: Package temperature/speed normal
```

**Comment by spandruvada** [comment]
Hi,
Can you run by adding an option 
--ignore-default-control

and get the same log. I am not worried about the "mce" messages. I want
to debug what causes temperature to stay below 75C after run of
workload.
Thanks,Srinivas

**Comment by benzea** [comment]
This is with debug log level and --ignore-default-control

[thermald.log](https://github.com/intel/dptfxtract/files/3202649/thermald.log)

**Comment by benzea** [comment]
With regard to the MCE messages. Is it completely normal that those happen? If yes, then I suspect it might make sense to downgrade them from the "crticial" level that they have to something less sever.

**Comment by spandruvada** [comment]
From the logs, I don't see any thermal throttling triggered this. I
think we are hitting some power limit.Try this:
Disable thermald and reboot, to take this out of picture.
Then run in one window#turbostat --debug  --show
Package,Core,CPU,PkgWatt,RAMWatt,PKG_%,RAM_%
Run your workload 
Attach the turbostat output when you see that temperature down to 75C.
Thanks,Srinivas

**Comment by benzea** [comment]
Sorry for the delay, here the turbostat output. Seems like the CPU gets throttled to around 15W:

[turbostat.log.txt](https://github.com/intel/dptfxtract/files/3228616/turbostat.log.txt)

As requested, this is without thermald running.

**Comment by benzea** [comment]
Again with the spew that goes to stderr:

[turbostat.log.txt](https://github.com/intel/dptfxtract/files/3228622/turbostat.log.txt)

**Comment by spandruvada** [comment]
As per the turbostat log , the TDP of this platform is 15 W.
cpu0: MSR_PKG_POWER_INFO: 0x00000078 (15 W TDP, RAPL 0 - 0 W, 0.000000 sec.)

So CPU will be throttled at 15W as the platform is designed. So from software we can’t change that safely.

Thanks,
Srinivas

**Comment by superm1** [comment]
In that case it seems like the mce events are deceptive; shouldn't they be indicating power for the reason to be throttled?

**Comment by gicmo** [comment]
@superm1 exactly what I was thinking. I am also wondering about what @benzea said about MCE thermal issues currently being critical. Are they really if it just self-regulates? Or can they really be ciritical on some models?

**Comment by superm1** [comment]
Glancing through the mce code (https://github.com/torvalds/linux/blob/9c7db5004280767566e91a33445bf93aa479ef02/arch/x86/kernel/cpu/mce/therm_throt.c#L149) it looks to me at a glance although there is a way to pass in `POWER_LIMIT_EVENT`S to the interrupt handler that there is no special logic to output that a `POWER_LIMIT_EVENT` was encountered, it's just silently not output.
I'd think that outputting those would probably help clarify what's going on when this happens.

**Comment by benzea** [comment]
The MCE events are actually over-temperature events. When the load starts initially the CPU draws a lot more power than the 15W and the package actually does get really hot (and I can see that the performance is much higher right after starting the load).

**Comment by spandruvada** [comment]
From the very first log, I can see that the temperature is very close to throttle temperature

thd_cdev_set_state temperature 95000:97000 index:9 state:1 :zone:11 trip_id:0 target_state_valid:0 target_value :27000000 force:0

At 15 W you are hitting throttling temperature. Since we poll at software at slower rate so we don’t catch but CPU catches and throttle. We can try reduce poll interval via thermald command line and try.

Thanks,
Srinivas

**Comment by benzea** [comment]
OK, so I just installed Windows 10 on the same machine. Running cpuburn there and looking at the information in AIDA after a long time I see:
 
* Core Temperature: 83-85°C (never higher, sometimes a bit lower)
* Long term Wattage (CPU Package): ~22 W

This is *much* higher than the 75°C and 15W we are seeing on Linux. Maybe I am missing something, but it really looks like a standard Windows is getting a lot more CPU power out of the system than we are.

**Comment by spandruvada** [comment]
On Wed, 2019-05-29 at 03:01 -0700, Benjamin Berg wrote:
> OK, so I just installed Windows 10 on the same machine. Running
> cpuburn there and looking at the information in AIDA after a long
> time I see:
> 
> 
> Core Temperature: 81-85°C (not higher)
> Long term Wattage: ~22 W
> 
> This is much higher than the 75°C and 15W we are seeing on Linux.
> Maybe I am missing something, but it really looks like a standard
> Windows is getting a lot more CPU power out of the system them we
> are.

Can you build thermald? There is a branch called v1_9_development,
where I have added change to be more active change of power limits.
https://github.com/intel/thermal_daemon/commits/v1.9_development
Thanks,Srinivas

**Comment by superm1** [comment]
Presumably you mean to use the `thermal-conf.xml.auto` generated by `dptfxtract` with this branch too right?

**Comment by spandruvada** [comment]
On Wed, 2019-05-29 at 09:50 -0700, Mario Limonciello wrote:
> Presumably you mean to use the thermal-conf.xml.auto generated by
> dptfxtract with this branch too right?
Yes.

Thanks,
Srinivas



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/intel/dptfxtract/issues/6?email_source=notifications\u0026email_token=AA5ALNSEPM62OBXL2E3SKRDPX2X6LA5CNFSM4HOCETVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWP6RYI#issuecomment-497019105",
"url": "https://github.com/intel/dptfxtract/issues/6?email_source=notifications\u0026email_token=AA5ALNSEPM62OBXL2E3SKRDPX2X6LA5CNFSM4HOCETVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWP6RYI#issuecomment-497019105",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by benzea** [comment]
The new version doesn't make a difference here (at least on the long run). The wattage still drops below 15W after a short amount of time.

**Comment by spandruvada** [comment]
Do you have thermald log?

Thanks,
Srinivas



________________________________________

**Comment by spandruvada** [comment]
I am on vacation so can't try on 9370 till later June. I want to also
try in addition to the new version of thermald with the latest kernel
5.2-rc*.The 5.2-rc* is a requirement as this has some change.
# cd /sys/bus/acpi/devices/INT3400:00/physical_node/uuids#
lsavailable_uuids  current_uuid# cat available_uuids 63BE270F-1C11-
48FD-A6F7-3AF253FF3E2D9E04115A-AE87-4D1C-9500-0F3E340BFE75# cat
current_uuid INVALID# echo "9E04115A-AE87-4D1C-9500-0F3E340BFE75" >
current_uuid # cat current_uuid 9E04115A-AE87-4D1C-9500-0F3E340BFE75
Then run thermald.
Thanks,Srinivas

**Comment by superm1** [comment]
it looks like email client mangled that.  I think this is what you meant, right?
```
# cd /sys/bus/acpi/devices/INT3400:00/physical_node/uuids
# ls
available_uuids  current_uuid
# cat available_uuids 
63BE270F-1C11-48FD-A6F7-3AF253FF3E2D 9E04115A-AE87-4D1C-9500-0F3E340BFE75
# cat current_uuid 
INVALID
# echo "9E04115A-AE87-4D1C-9500-0F3E340BFE75" >current_uuid 
# cat current_uuid
9E04115A-AE87-4D1C-9500-0F3E340BFE75
```

**Comment by benzea** [comment]
OK; I'll redo the test, attach the log and see if I can do this on a 5.2 RC kernel after the weekend (I don't have the device at home).

Have a nice holiday!

**Comment by spandruvada** [comment]
On Fri, 2019-05-31 at 15:21 -0700, Mario Limonciello wrote:
> it looks like email client mangled that.  I think this is what you
> meant, right?
Correct.

**Comment by benzea** [comment]
Here you go, my simple (just a few shell busy loops this time) load again stayed below 15W in the long run. It did exceed the 15W by a large margin for a short period of time.

[thermald.log.txt](https://github.com/intel/dptfxtract/files/3247172/thermald.log.txt)
[uname-a.txt](https://github.com/intel/dptfxtract/files/3247173/uname-a.txt)
[UUIDs.txt](https://github.com/intel/dptfxtract/files/3247174/UUIDs.txt)

**Comment by spandruvada** [comment]
Thanks. We have one 9370 in lab, so need to take a look, how windows
can keep higher power limits.
-Srinivas

**Comment by spandruvada** [comment]
Unfortunately I am not able to get 9370. So please try to read some MMIO regs (iotools package can be download from https://code.google.com/archive/p/iotools/)

sudo ./iotools mem_read32 0xfed15938

After running thermald new version from the development branch

sudo rdmsr 0x610

sudo ./iotools mem_read64 0xfed159a0

Please send the output to me for all commands
If the outputs from the MSR and MMIO reads are not same, then make them same. Write output of MSR 0x610 via iotools mem_write64

./iotools mem_write64 0xfed159a0 <value from MSR 0x610 includin 0x,,,>

Now run the workload and see whether power drops immediately as before

**Comment by benzea** [comment]
OK,

```
# After starting an up to date thermald:
# uname -a
Linux localhost-live 5.2.0-0.rc2.git1.2.fc31.x86_64 #1 SMP Fri May 31 19:01:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# ./iotools mem_read32 0xfed15938
0x000a0e03

# rdmsr 0x610
420198009c80d8

# ./iotools mem_read64 0xfed159a0
0x0042819800dd8078

# ./iotools mem_write64 0xfed159a0 0x420198009c80d8
# ./iotools mem_read64 0xfed159a0
0x00420198009c80d8

# Running simple load (just a few bash loops), turbostat now gives me:
# turbostat --debug --show Package,Core,CPU,PkgWatt,RAMWatt,PKG_%,RAM_%
[...]
Core	CPU	PkgWatt	RAMWatt	PKG_%	RAM_%
-	-	21.96	0.51	0.00	0.00
0	0	21.96	0.51	0.00	0.00
0	4
1	1
1	5
2	2
2	6
3	3
3	7
```

Writing the old value back into the register makes it drop again after a while.

Btw. do you maybe happen to be at LPC? Might be able to talk a bit there.

**Comment by spandruvada** [comment]
So you think your problem is fixed with this? I will implement in the
thermald code what is done by the tools here.

I go to LPC when in North America. This time I will try but since in
Europe, may have difficulty.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
I assume this problem gets resolved after iotools writes.
Please try without those iotools command the thermald from v1.9_development (https://github.com/intel/thermal_daemon/tree/v1.9_development)

Add --workaround-enabled option.
For example
 sudo ./thermald --no-daemon --loglevel=info --workaround-enabled

To verify that this option worked
#sudo iotools mem_read64 0xfed159a0

The BIT 15 of the result displayed should be 0.

**Comment by benzea** [comment]
For me/us it is the other way around, and North America is a bit far :)

Correct, the write resolved the issue. Thanks for the patch, it does look really promising, I'll test at the start of next week (probably Monday, maybe only on Tuesday)!

**Comment by superm1** [comment]
Since /dev/mem gets locked down on some distros would you consider to do this in kernel space instead?

**Comment by spandruvada** [comment]
We already submitted patch for rapl-mmio support. The thermald 1.9
version is already looking for it.I hope it can be merged to 5.3.
Thanks,Srinivas

**Comment by benzea** [comment]
@spandruvada, sorry for the delay. The patch works fine when I pass `--workaround-enabled` on the command line. So that is good news!

Will we be able to set the appropriate registers automatically on affected machines in the future? I guess that will need a bit more work, maybe also additional support in `dptfxtract`.

**Comment by benzea** [comment]
> Will we be able to set the appropriate registers automatically on affected machines in the future?

Ah, let me guess. The earlier patches that already do this and it will just start working with a 5.3 kernel?

**Comment by spandruvada** [comment]
On Thu, 2019-07-04 at 02:21 -0700, Benjamin Berg wrote:
> > Will we be able to set the appropriate registers automatically on
> > affected machines in the future?
> 
> Ah, let me guess. The earlier patches that already do this and it
> will just start working with a 5.3 kernel?
In 5.3, we don't have to do dev/mem magic.I am trying to check behavior
on systems and add some checks so that we don't need this -workaround
option meanwhile for this to work.

Thanks,Srinivas

**Comment by ramcq** [comment]
@spandruvada Can you confirm which patches in 5.3 will allow the TDP to peak at higher levels? I had a dig through linux-next. We have lockdown patches in our kernel enabled for secure boot so /dev/mem from thermald won't be too handy. :)

**Comment by spandruvada** [comment]
Search for "intel_rapl: RAPL changes for 5.3". They are reposted today.
Since it had dependency on some other patches in other trees, it had to
wait for another push.
Thanks,Srinivas

**Comment by superm1** [comment]
@ramcq here is the series: https://lore.kernel.org/linux-pm/1562766278-7099-1-git-send-email-rui.zhang@intel.com/T/#t

**Comment by superm1** [comment]
If I understand correctly you need that series going into 5.3 to export the rapl MMIO interface to userspace but still need at least this commit from your thermald development branch https://github.com/intel/thermal_daemon/commit/937a2c5e33561af3c0f066e2bbbcd672481d49cf to activate the feature at the right times.

**Comment by spandruvada** [comment]
On Wed, 2019-07-10 at 18:56 -0700, Mario Limonciello wrote:
> If I understand correctly you need that series going into 5.3 to
> export the rapl MMIO interface to userspace but still need at least
> this commit from your thermald development branch 
> intel/thermal_daemon@937a2c5 to activate the feature at the right
> times.
Correct.

Thanks,
Srinivas

**Comment by tlbdk** [comment]
The Dell XPS 9380 seems to exhibit pretty much the same behaviour, will the upcoming fixes and patches also cover that?

**Comment by spandruvada** [comment]
On Mon, 2019-07-22 at 13:01 -0700, Troels Liebe Bentsen wrote:
> The Dell XPS 9380 seems to exhibit pretty much the same behaviour,
> will the upcoming fixes and patches also cover that?
Yes.
Thanks,Srinivas

**Comment by superm1** [comment]
@spandruvada given 5.3-rc1 was released, will you be able to merge those into a new thermald release soon?  I think that should help more people use this stuff.

**Comment by spandruvada** [comment]
I have merged 1.9 changes and also dptfxtract to the latest to the master branch. Please try.
I have not tagged the thermald release to get if there are some issues with build or static analysis. 
Just update to kernel 5.3-rc1 and use dpftxtract 1.4.1 to generate configuration files. Then try the latest thermald. 
I encourage to build ThermalMonitor, in that way we can monitor the temperature trends.

**Comment by ghost** [comment]
@spandruvada I'm running Ubuntu 18.04 HWE on a Dell XPS 9380.  I downloaded thermald 1.9.1 and the most recent dptfxtract.  I'm running thernald with --workaround-enabled.  Your patch works well,  first time my laptop has run at full speed since I bought it.   But it looks like it is competing with some other system on limiting the power consumption.  When plugged into power, under load power is not limited to 15W - but then after a while it cuts back to power consumption for a time, and then comes up again.  

I've attached an s-tui screenshot.

![Screenshot from 2019-12-07 13-20-51](https://user-images.githubusercontent.com/57816304/70367506-a48cd000-18f4-11ea-8c8e-1ab550c363b2.png)

Happy to log any investigations that will help.

**Comment by spandruvada** [comment]
Thanks for the graph. What is the time scale of the graph? Any chance of running with ThermalMonitor? It will show other temperature sensor.
Also system with hit power limit, which it can't sustain, so it will drop and again pickup.

Run thermald from command line and send the output

#thermald --no-daemon --loglevel=info --dbus-enable


Thanks,
Srinivas

On Fri, 2019-12-06 at 18:22 -0800, jules-ofs wrote:

@spandruvada<https://github.com/spandruvada> I'm running Ubuntu 18.04 HWE on a Dell XPS 9380. I downloaded thermald 1.9.1 and the most recent dptfxtract. I'm running thernald with --workaround-enabled. Your patch works well, first time my laptop has run at full speed since I bought it. But it looks like it is competing with some other system on limiting the power consumption. When plugged into power, under load power is not limited to 15W - but then after a while it cuts back to power consumption for a time, and then comes up again.

I've attached an s-tui screenshot.

[Screenshot from 2019-12-07 13-20-51]<https://user-images.githubusercontent.com/57816304/70367506-a48cd000-18f4-11ea-8c8e-1ab550c363b2.png>

Happy to log any investigations that will help.

**Comment by ghost** [comment]
Thanks for the prompt reply @spandruvada 

Here is the logging you requested.
Timescale in the s-tui screenshot is one bar per second.
Polling period for ThermalMonitor is two seconds.  This makes the graphs roughly align.

#./thermald --no-daemon --loglevel=info --dbus-enable --workaround-enabled |& tee ~/thermald.log

[thermald.log](https://github.com/intel/dptfxtract/files/3935738/thermald.log)
[ThermalMonitor.log](https://github.com/intel/dptfxtract/files/3935739/ThermalMonitor.log)

![s-tui](https://user-images.githubusercontent.com/57816304/70382572-8685a500-19b2-11ea-8bac-5131db454e5d.png)
![ThermalMonitor](https://user-images.githubusercontent.com/57816304/70382576-8be2ef80-19b2-11ea-8c2f-a6c9111d741b.png)

**Comment by spandruvada** [comment]
You see a dip when SEN4 reaches 49C. The laptop thermal configuration is calling for changing power limit to 23W. So this is correct behavior as per the configuration.

**Comment by benzea** [comment]
Hmm, I am guessing this bug can be closed. The original issues have been resolved in thermald quite a long time ago.
